In [1]:
from sklearn import metrics
import numpy as np
from keras.datasets import fashion_mnist
(x_train, y_train), (x_test, y_test) = fashion_mnist.load_data()
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

x_train = np.array(x_train).reshape(-1, 784)
x_test = np.array(x_test).reshape(-1, 784)
print(x_train.shape)
print(x_test.shape)

/home/wlun/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


(60000, 28, 28)
(60000,)
(10000, 28, 28)
(10000,)
(60000, 784)
(10000, 784)


In [6]:
from sklearn.neighbors import KNeighborsClassifier

neigh = KNeighborsClassifier(n_neighbors=15)
neigh.fit(x_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=15, p=2,
           weights='uniform')

In [7]:
predicted_output = neigh.predict(x_test)

In [8]:

from sklearn.externals import joblib
joblib.dump(neigh, 'fashion-mnist-model-knn.pkl') 

print(metrics.accuracy_score(y_test, predicted_output))
print(metrics.confusion_matrix(y_test, predicted_output))

0.8462
[[864   0  19  18   7   0  81   1  10   0]
 [  8 957   7  19   4   0   4   0   1   0]
 [ 17   2 799   6  84   0  91   0   1   0]
 [ 34   4  15 872  37   0  37   0   1   0]
 [  0   0 110  29 759   0  99   0   3   0]
 [  1   0   0   2   0 779   7 121   2  88]
 [184   1 135  24  73   0 568   0  15   0]
 [  0   0   0   0   0   2   0 955   0  43]
 [  2   1  19   2   9   0  14   7 944   2]
 [  0   0   1   0   0   0   1  33   0 965]]
